### ISSUE TITLE
Nested folders not working in windows

### ISSUE THREAD

**Issue by socrat3z** [snaerth/create-react-component-folder#2]
Having the latest package installed, while trying to create Button component on Windows with the following syntax
`crcf components/Button`
the "Button" folder is created in root, and not in the "components" folder

**Comment by snaerth** [comment]
Thank you for pointing that out. I will fix it in the to night or tomorrow and let you know :)

**Comment by snaerth** [comment]
@socrat3z What Node version are you running?

**Comment by socrat3z** [comment]
@snaerth  it's v9.5.0

**Comment by Aidurber** [comment]
@snaerth After skimming through the code I believe the issue lies in
```javascript
function getComponentParentFolder(componentPath) {
  if (componentPath !== -1) {
    return componentPath.substring(0, componentPath.lastIndexOf(lastSlash) + 1);
  }

  return componentPath;
}
```

Specifically `  if (componentPath !== -1) {`
Shouldn't that be `if(componentPath.lastIndexOf(lastSlash) !== -1)`

That fixes the issue with an initialisation of `component/Button` but breaks it for `Button`.
It produces a folder called "ButtonButton"

**Comment by snaerth** [comment]
Thank you @Aidurber  for pointing it out. I am a little busy today but I promise to find a permanent solution tomorrow and fix the issue for good.

**Comment by snaerth** [comment]
I have fixed the windows issue in version 0.0.35. Can you @Aidurber  and @socrat3z  confirm :)

**Comment by skyboyer** [comment]
issue is still reproduced for 0.1.0

**Comment by flyfishMT** [comment]
Hi, I have this issue on Windows 10 as well. I ran on the Ubuntu shell included with Windows - Windows Subsystem for Linux - and it creates the module in the sub-path correctly, but when ran from Windows command shell, it creates the component folder in the CWD.  I need it to work on the command shell because I'm running from the terminal in VS Code.

**Comment by aijazkhan81** [comment]
Doesn't happen for me as well. It creates the component in whatever folder I am in. Doesn't respect the folder path I provide.
